@echo off
echo Cloud Gaming Console System
echo build 0013b
echo.
echo Starting Remote Gaming System....
call "C:\Files\start_machine.bat" >nul
echo Remote Gaming System Started....
echo Waiting for Remote Gaming System to be READY....
call "C:\Files\wait_machine.bat" >nul
echo Remote Gaming System Ready...Waiting 30 seconds....
timeout /t 30
echo Opening Parsec Session....
"C:\Program Files\Parsec\parsecd.exe" server_id=[CHANGEMETOSERVERID] >nul
echo.
echo Press any key to SHUTDOWN the remote gaming system....
pause>null
call "C:\Files\stop_machine.bat" >nul
echo Remote Gaming System Shutdown Started....
echo Waiting for Remote Gaming System to shutdown....
call "C:\Files\wait_machine_off.bat" >nul
echo Remote Gaming System is down....
timeout /t 30
